pipeline {
    agent any
  
    stages {
        stage('Build') {
            steps {
                echo 'test build'
            }
        }
        stage('Test') {
            steps {
                echo "test feat1"
            }
        }
    }
}
